import {
    PLATFORM_PERMISSION,
} from '../../constants/platformPermissions.constants.js';
import {
    PLATFORM_TEAM_ROLE_KEY,
} from '../../constants/platformTeam.constants.js';
import {
    ACTIVE_PLATFORM_PERMISSION_REGISTRY,
} from '../../config/applicationPlatformPermission.registry.js';


const PLATFORM_ADMIN_PERMISSIONS = Object.freeze([
    PLATFORM_PERMISSION.OVERVIEW_READ,
    PLATFORM_PERMISSION.CAPABILITIES_READ,
    PLATFORM_PERMISSION.USERS_READ,
    PLATFORM_PERMISSION.USERS_DISABLE,
    PLATFORM_PERMISSION.USERS_ENABLE,
    PLATFORM_PERMISSION.USERS_REVOKE_SESSIONS,
    PLATFORM_PERMISSION.WORKSPACES_READ,
    PLATFORM_PERMISSION.WORKSPACES_SUSPEND,
    PLATFORM_PERMISSION.WORKSPACES_REACTIVATE,
    PLATFORM_PERMISSION.PLANS_READ,
    PLATFORM_PERMISSION.PLANS_CREATE,
    PLATFORM_PERMISSION.PLANS_UPDATE,
    PLATFORM_PERMISSION.PLANS_ARCHIVE,
    PLATFORM_PERMISSION.SUBSCRIPTIONS_READ,
    PLATFORM_PERMISSION.SUBSCRIPTIONS_GRANT_TRIAL,
    PLATFORM_PERMISSION.SUBSCRIPTIONS_UPDATE,
    PLATFORM_PERMISSION.SUBSCRIPTIONS_CANCEL,
    PLATFORM_PERMISSION.SUBSCRIPTIONS_RESUME,
    PLATFORM_PERMISSION.ENTITLEMENT_OVERRIDES_READ,
    PLATFORM_PERMISSION.ENTITLEMENT_OVERRIDES_CREATE,
    PLATFORM_PERMISSION.ENTITLEMENT_OVERRIDES_UPDATE,
    PLATFORM_PERMISSION.ENTITLEMENT_OVERRIDES_REVOKE,
    PLATFORM_PERMISSION.AUDIT_LOGS_READ,
    PLATFORM_PERMISSION.TEAM_READ,
    PLATFORM_PERMISSION.TEAM_INVITE,
    PLATFORM_PERMISSION.TEAM_INVITATION_RESEND,
    PLATFORM_PERMISSION.TEAM_INVITATION_REVOKE,
    PLATFORM_PERMISSION.TEAM_MEMBER_ROLE_UPDATE,
    PLATFORM_PERMISSION.TEAM_MEMBER_SUSPEND,
    PLATFORM_PERMISSION.TEAM_MEMBER_REACTIVATE,
    PLATFORM_PERMISSION.TEAM_MEMBER_REVOKE,
    PLATFORM_PERMISSION.ROLES_READ,
    PLATFORM_PERMISSION.ROLES_CREATE,
    PLATFORM_PERMISSION.ROLES_UPDATE,
    PLATFORM_PERMISSION.ROLES_ARCHIVE,
]);

const TECHNICAL_SUPPORT_PERMISSIONS = Object.freeze([
    PLATFORM_PERMISSION.OVERVIEW_READ,
    PLATFORM_PERMISSION.CAPABILITIES_READ,
    PLATFORM_PERMISSION.USERS_READ,
    PLATFORM_PERMISSION.USERS_REVOKE_SESSIONS,
    PLATFORM_PERMISSION.WORKSPACES_READ,
    PLATFORM_PERMISSION.PLANS_READ,
    PLATFORM_PERMISSION.SUBSCRIPTIONS_READ,
    PLATFORM_PERMISSION.ENTITLEMENT_OVERRIDES_READ,
    PLATFORM_PERMISSION.AUDIT_LOGS_READ,
]);

const COMMERCIAL_SUPPORT_PERMISSIONS = Object.freeze([
    PLATFORM_PERMISSION.OVERVIEW_READ,
    PLATFORM_PERMISSION.CAPABILITIES_READ,
    PLATFORM_PERMISSION.USERS_READ,
    PLATFORM_PERMISSION.WORKSPACES_READ,
    PLATFORM_PERMISSION.PLANS_READ,
    PLATFORM_PERMISSION.SUBSCRIPTIONS_READ,
    PLATFORM_PERMISSION.SUBSCRIPTIONS_GRANT_TRIAL,
    PLATFORM_PERMISSION.ENTITLEMENT_OVERRIDES_READ,
]);

const CUSTOMER_SUPPORT_PERMISSIONS = Object.freeze([
    PLATFORM_PERMISSION.OVERVIEW_READ,
    PLATFORM_PERMISSION.USERS_READ,
    PLATFORM_PERMISSION.WORKSPACES_READ,
    PLATFORM_PERMISSION.PLANS_READ,
    PLATFORM_PERMISSION.SUBSCRIPTIONS_READ,
]);

const SYSTEM_PLATFORM_ROLE_PRESETS = Object.freeze([
    Object.freeze({
        key: PLATFORM_TEAM_ROLE_KEY.SUPER_ADMIN,
        name: 'Super administrateur',
        description:
            'Autorité administrative maximale de la Plateforme.',
        permissions:
            ACTIVE_PLATFORM_PERMISSION_REGISTRY.definitions.map(
                ({ key }) => key,
            ),
    }),
    Object.freeze({
        key: PLATFORM_TEAM_ROLE_KEY.PLATFORM_ADMIN,
        name: 'Administrateur de la Plateforme',
        description:
            'Administration courante étendue sans les opérations réservées au Super administrateur.',
        permissions: PLATFORM_ADMIN_PERMISSIONS,
    }),
    Object.freeze({
        key: PLATFORM_TEAM_ROLE_KEY.TECHNICAL_SUPPORT,
        name: 'Support technique',
        description:
            'Diagnostic technique et assistance sans pouvoir commercial ou terminal.',
        permissions: TECHNICAL_SUPPORT_PERMISSIONS,
    }),
    Object.freeze({
        key: PLATFORM_TEAM_ROLE_KEY.COMMERCIAL_SUPPORT,
        name: 'Support commercial',
        description:
            'Consultation commerciale et attribution contrôlée des essais.',
        permissions: COMMERCIAL_SUPPORT_PERMISSIONS,
    }),
    Object.freeze({
        key: PLATFORM_TEAM_ROLE_KEY.CUSTOMER_SUPPORT,
        name: 'Support client',
        description:
            'Assistance principalement en lecture sur les données administratives utiles.',
        permissions: CUSTOMER_SUPPORT_PERMISSIONS,
    }),
]);


export {
    COMMERCIAL_SUPPORT_PERMISSIONS,
    CUSTOMER_SUPPORT_PERMISSIONS,
    PLATFORM_ADMIN_PERMISSIONS,
    SYSTEM_PLATFORM_ROLE_PRESETS,
    TECHNICAL_SUPPORT_PERMISSIONS,
};
